apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/shoreline2/neptune.git'
    targetRevision: HEAD
    path: k8s/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
